unique_ids:
  assets:
    capybara.jpeg: '1730023686497676802364297.2603'
    standard-page.html: LBCTKHLMW5EHDWOSJNOCKRXT653VQ7KD
    theme.css: IMECZLPE6PVI2P3YZ4ANI6BFTIALGZ6N
  forms:
    CommentModal: 2VBFCUQGFB7JSL5COEVJFDYWEJTGEAUW
    CommentModal.ItemTemplate1: HLLH44QHRZLF5Z4T5MGRIR3KO6VS6KJI
    EditableLink: BLOOJHJMBIA4A243RQOZTB3AUIYQ7SNJ
    Frame: 3MVXI3ZSVZQHTPX6ZQ75A7XYMHCCJ73J
    LogoutScreen: DBEENFXBZRMI4HN4QSSWCMIM3DHSY6VL
    NewColumnModal: Z6M2GV7MEVLGACD7GFGDDLITG3HYRMQ6
    ProjectCard: Z7OTTQRBZ7CPO7S2WS7PNKITWK2BWR7Y
    ProjectList: YLBII5CUFKR6GN25OT57UOBMWQJ6X577
    ProjectView: KEDV2KWCNH7RX5J2EFR6RIX2LD7NPIDK
    ProjectView.RowTemplate3: GIO4GK53Q24CP6HLM7LLEGECCF3HOSNW
    ProjectView.RowTemplate3.RowTemplate1: 2ZNOR7KMIGHNS4LSN4G6RNQO6KQ2EU2P
    TagComponent: K7MN5JHADWPTPUUBUQY6V4WFBL7KTH5Q
  modules:
    GlobalVars: 7NFSON5SFDC5WZRASRIRTBD7LRIIVP5A
    StartupModule: SUVIYENX4LVJAUCKKCUCMMGLGMDMS5BC
  scripts: {}
  server_modules:
    ColumnModule: '1730018343600596273390514.217'
    CommentModule: '1730019446639941735906470.4076'
    ProjectModule: '1730019648847588620533877.9276'
    RowsModule: '1730019373433769601941554.0785'
    ServerModule1: FQ5WXBXJPNKJYTBUFW2OEBQJBGSI5BWC
    TasksModule: '1730106073397696517491370.3778'
